# Generated by Django 5.2.6 on 2025-10-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
    """, """
            DELETE FROM store_collection
            WHERE title='collection1'
        """)
    ]
