# Generated by Django 5.2.6 on 2025-10-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_auto_20251004_2035"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="Product",
            new_name="product",
        ),
    ]
